name: 🔧 Bug Report
description: Create a report to help us improve
labels:
- bug
body:
- type: textarea
  attributes:
    label: Describe the bug
    placeholder: A clear and concise description of what the bug is.
  validations:
    required: true
- type: input
  attributes:
    label: Affected File
    placeholder: Add file name or a link to the associated file.
  validations:
    required: false
- type: input
  attributes:
    label: Affected Line
    placeholder: Add code line number.
  validations:
    required: false   
- type: textarea
  attributes:
    label: To Reproduce
    placeholder: |
      Steps to reproduce the behaviour
      1. Step 1
      2. Step 2.
      3. See error
  validations:
    required: false
- type: textarea
  attributes:
    label: Minimum reproducible example
    description: Copy and paste the code from the editor that you used in between the back-ticks.
    value: |
      ```



      ```
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    placeholder: Add any other context about the problem here.
  validations:
    required: false