name: "📚 Documentation Issue"
description: Report issues in our documentation, such as broken links, typos and missing parts.
labels: 
- docs
body:
- type: textarea
  attributes: 
    label: Describe the issue
    placeholder: A clear and concise description of what the issue is.
  validations:
    required: true
- type: input
  attributes:
    label: Affected Page
    placeholder: Add a link to the associated page.
  validations:
    required: true
- type: input
  attributes:
    label: Affected Line
    placeholder: Add code line number.
  validations:
    required: true