name: "💡 Feature Request"
description: Suggest an idea for this project
labels: 
- feature
body:
- type: textarea
  attributes: 
    label: Describe the solution you'd like
    placeholder: A clear and concise description of what you want to happen.
  validations:
    required: true